typo fixes
motion-canvas/motion-canvas pull request #191
Opened 2023-02-05 02:21 UTC by dnoenickx

2023-02-05 02:22 UTC, dnoenickx commented on packages/2d/src/components/Layout.ts
>     * represents the `height`.
not a typo, but making it consistent for width and height

2023-02-06 03:00 UTC, aarthificial requested changes

2023-02-06 03:00 UTC, aarthificial commented on packages/core/src/flow/chain.ts
> + *   rect.cornerRadius(20, 3),
This is actually outdated. It should be simply:
```suggestion
 *   rect.radius(20, 3),
```

2023-02-06 03:01 UTC, aarthificial commented
The checks have failed but you don't need to worry about this. In the future be sure to name your commits like this:
```
docs: typo fixes
```
In order to meet the [Angular Commit Message Conventions](https://github.com/angular/angular/blob/main/CONTRIBUTING.md#commit).

2023-02-06 15:40 UTC, merged