docs: clarification on scaffolding process
motion-canvas/motion-canvas pull request #200
Opened 2023-02-05 14:10 UTC by 20milliliter

Clarifies that to use Motion Canvas, cloning the repo is not required.

Issue #196

2023-02-05 15:27 UTC, yemibox51 approved these changes

2023-02-05 16:16 UTC, VinithS requested changes
Seems redundant. How to being using is already defined in [quickstart guide](https://motion-canvas.github.io/docs/quickstart/).

And if you are a programmer, you probably know how to get started with contributing.

2023-02-06 03:10 UTC, aarthificial commented
Agree with @VinithS
Unless there's something in the docs that I forgot about, that would suggest you need to clone the repo, @20milliliter?

2023-02-06 04:31 UTC, aarthificial commented
I've noticed that this PR originates [from this issue](https://github.com/motion-canvas/motion-canvas/issues/196#issuecomment-1417869868) and I must disagree. The issue was caused by the fact that @FilledStacks used to participate in the early access of Motion Canvas and had their npm configured to fetch mc packages from GitHub. **They did not try to clone the repo** and I don't see how anyone would be confused about that.

2023-02-06 04:31 UTC, closed without merging