feat(core,create,vite-plugin): update vite from v3 to v4
motion-canvas/motion-canvas pull request #495
Opened 2023-03-08 16:56 UTC by guifeliper

This PR updated Vite version from v3 to v4 is mentioned here #197. 

I have run all the build commands and no error was found.

2023-03-08 22:19 UTC, aarthificial requested changes
`vitest` is still causing v3 to be installed:

![image](https://user-images.githubusercontent.com/64662184/223864011-0239c783-ef88-46ae-8ed9-807675710e03.png)

2023-03-13 15:59 UTC, guifeliper commented
@aarthificial I have updated as you mentioned! By the way, thank you for showing me the npm ls <lib>, I didn't remember about this.

2023-03-14 20:41 UTC, aarthificial approved these changes

2023-03-16 01:44 UTC, merged

2023-03-16 01:47 UTC, aarthificial commented
Thanks for the PR!