fix(2d): clip Txt by default
motion-canvas/motion-canvas pull request #525
Opened 2023-03-14 20:38 UTC by ribru17

Clip Txt by default to prevent confusing behavior where text clips only while animating. I only enacted this change for text height as I didn't know whether it would potentially affect text wrapping in the future.

Fixes #465

2023-03-14 21:22 UTC, aarthificial requested changes
Text still isn't clipped in the same way as when using cache.

Example with text with limited width:
![image](https://user-images.githubusercontent.com/64662184/225138569-57d5d1ef-47f7-43ff-a359-0e125324d338.png)
```ts
view.add(
  <>
    <Txt fill={'white'} x={-200} width={100} cache>
      Lorem ipsum
    </Txt>
    <Txt fill={'white'} x={200} width={100}>
      Lorem ipsum
    </Txt>
  </>,
);
````

Example with wrapped text:
![image](https://user-images.githubusercontent.com/64662184/225138308-38998bb1-b387-45f8-b38a-a4955aab17b1.png)
```ts
view.add(
  <>
    <Txt fill={'white'} x={-200} width={320} height={200} textWrap cache>
      Lorem ipsum dolor sit amet, consectetur adipisicing elit. Est harum
      illum, ipsam iure laborum modi molestiae mollitia provident quod
      sapiente! Aperiam asperiores beatae fuga iusto nostrum numquam odit
      totam, vitae!
    </Txt>
    <Txt fill={'white'} x={200} width={320} height={200} textWrap>
      Lorem ipsum dolor sit amet, consectetur adipisicing elit. Est harum
      illum, ipsam iure laborum modi molestiae mollitia provident quod
      sapiente! Aperiam asperiores beatae fuga iusto nostrum numquam odit
      totam, vitae!
    </Txt>
  </>,
);
```

2023-03-14 21:22 UTC, aarthificial commented on packages/2d/src/components/Txt.ts
> +    context.clip(clipPath);
Clipping should be done in the `draw` method. `drawText` is called for each text segment.

`this.computedSize()` should be used to acquire the bounding box, analogically to how `Layout` does it.

2023-03-14 21:24 UTC, aarthificial commented
This PR only partially resolves #465, as the `clip` property is still not being respected by the `Txt` node

2023-03-14 21:28 UTC, aarthificial commented
> to prevent confusing behavior

I think this is still a confusing behavior. Ideally, the cache size should be increased so that the text never gets clipped, even when lowering the opacity. The `clip` property would then enable clipping like in all other Shape nodes.

2023-03-14 22:07 UTC, ribru17 commented
Thanks for the feedback. I'll start working on changes

2023-04-28 09:07 UTC, ksassnowski commented
@ribru17 It's been a while since the last review. Are you still planning to continue with this PR?

2023-04-28 17:22 UTC, ribru17 commented
@ksassnowski Sorry I've been really busy I don't know if I will be able to continue any time soon, I'm open to someone else taking a look. I might not have time to dedicate to this for a couple months.

2023-05-21 04:05 UTC, nishchay7pixels commented
Picking this one up if everyone agree.

2023-10-26 09:30 UTC, rmhartog commented
> > to prevent confusing behavior
> 
> I think this is still a confusing behavior. Ideally, the cache size should be increased so that the text never gets clipped, even when lowering the opacity. The `clip` property would then enable clipping like in all other Shape nodes.

Based on this comment, I've created a PR for the cache bounding box of the `Txt` component in #836.

2023-11-04 17:46 UTC, closed without merging