CodeBlock: re-setting the signal to its default
motion-canvas/motion-canvas pull request #607
Opened 2023-04-05 21:45 UTC by gmile

Mention an alternative way to de-select all text: it can be done by setting
a value of `.selection()` signal to its default, e.g. "all selected"

2023-04-06 07:45 UTC, aarthificial requested changes

2023-04-06 07:45 UTC, aarthificial commented on packages/docs/docs/components/code-block.mdx
> +default, e.g. "all selected". For example:
I think you meant `i.e.` :
```suggestion
default, i.e. "all selected". For example:
```

2023-04-06 07:45 UTC, aarthificial commented on packages/docs/docs/components/code-block.mdx
> +```
Syntax highlighting:
````suggestion
```ts
````

2023-04-06 12:58 UTC, gmile commented
@aarthificial thanks for inline suggestions! Both are accepted now 🙇 Do you prefer all commits in a PR's branch to be squashed ahead of the merging to main branch?

2023-04-06 15:25 UTC, aarthificial commented
No, we squash PRs when merging anyway
You'll have to run prettier after applying my changes tho

2023-04-07 09:44 UTC, gmile commented
@aarthificial thanks for a quick review! I've decided to squash the commits to make `commitlint` happy and history a little bit cleaner. Made sure to have kept you as as co-author too.

2023-04-07 13:42 UTC, aarthificial approved these changes

2023-04-07 13:44 UTC, merged

2023-04-07 13:44 UTC, aarthificial commented
Thanks for the PR!