docs: document setting layout=false on a node
motion-canvas/motion-canvas pull request #613
Opened 2023-04-07 21:36 UTC by gmile

This documents change of node's properties after setting its `layout` to `false`

Fixes #449

2023-04-14 00:33 UTC, aarthificial requested changes

2023-04-14 00:33 UTC, aarthificial commented on packages/docs/docs/getting-started/layouts.mdx
> +Sometimes it can be useful to remove the node from the node tree. This way the
> remove the node from the node tree

That's not what disabling `layout` does. The node will still be the child of its parent, even when `layout` is disabled.

2023-04-14 00:33 UTC, aarthificial commented on packages/docs/docs/getting-started/layouts.mdx
> +node can be styled independently of its ancestor layout, as well as moved freely
> node can be styled independently of its ancestor layout

A node can always be styled independently. The goal of disabling `layout` is to regain control over the node's position and size. Or, in other words, to exclude it from the parent's layout.

2023-04-14 00:33 UTC, aarthificial commented on packages/docs/docs/getting-started/layouts.mdx
> +1. the node is moved to the place of origin, e.g. center of the scene,
That's not true. The node's position will be whatever the `position` property is set to. Enabling the layout does not change this property - it overrides it but the values are still kept in there.

2023-04-14 00:33 UTC, aarthificial commented on packages/docs/docs/getting-started/layouts.mdx
> +3. the node no longer inherits properties from its parent, such as text styling,
text styling are the only properties inherited by a node. "such as" implies that there are more which is not true.

2023-04-14 00:33 UTC, aarthificial commented on packages/docs/docs/getting-started/layouts.mdx
> +   property of an HTML node to `absolute` value.
I don't think mentioning `absolute` positioning from CSS here makes this clearer.
Our default positioning system is already described in the previous section.

2023-04-14 00:33 UTC, aarthificial commented on packages/docs/docs/getting-started/layouts.mdx
> +   height when calculating its own bounding box. Disabling a layout on a node
The layout system calculates the sizes and positions of nodes, not their bounding boxes. 
"Bounding box" has a specific meaning in Motion Canvas which is different from the size of a node.

2023-04-14 00:33 UTC, aarthificial commented on packages/docs/docs/getting-started/layouts.mdx
> +   children nodes follow `<Rect>`'s styling and direction,
I don't like the emphasis on "styling and direction" here.
The point of the `layout` property is to arrange the children into a layout by changing their sizes and postions.
Inheriting the text style is a secondary thing that's not yet described in other sections.
Additionally, this example doesn't even use text.

2023-04-28 08:35 UTC, ksassnowski commented
@gmile It's been a while since the last review. Do you still plan on continuing with this PR? Have you had time to address @aarthificial's comments yet?

2023-04-28 09:22 UTC, gmile commented
@ksassnowski I haven't had a chance to go over them, unfortunately. I intent to complete this, but I am also open to closing the issue for the time being. Closing for now to keep the tracker tidy 🙇

2023-04-28 09:22 UTC, closed without merging

2023-04-28 09:23 UTC, ksassnowski commented
Alright, thanks! Feel free to reopen the PR if you ever get around to working on it again 👍