feat(2d): add SVG component
motion-canvas/motion-canvas pull request #763
Opened 2023-07-04 04:27 UTC by levirs565

This will add `SVG` component. This component can render SVG and tween between two SVG.

This is part of [add Latex component pull request](https://github.com/motion-canvas/motion-canvas/pull/539).

## Tweening Algorithm

SVG tweening algorithm support insertion, deletion and tranformation. 

This algorithm also support SVG that contain 2 or more element with same id. When number of element with some id in source and target do not match, all element will be transformed wihout insertion or deletion. 

When number of element with some id in source is greater than number of element with that id then excess element will be transformed into target last element with that id.

```
[1, 2, 1, 3, 1] -> [1, 2, 3]
```

> Second and third source element with id 1 will be transformed into first target element with id 1.

When number of element with some id in source is lower than number of element with that id then source last element with that id will be cloned and then transformed target element that index is matched.

```
[1, 2, 3] --> [1, 2, 1, 3, 1]
```

> First source element with id 1 will cloned two time and the two item will transformed to second and third target element with id 1 respectively

This algorithm does not support moving item index. Why? Because moving item index cannot transformed/animated smoothly.

This algorithm will insert element based on previous element not index. Why? For simplicity. When, there are inserted element and element previous item is moved then the element will inserted after previous item.

```
[1, 2, 3] --> [1, 3, 5, 2]

result: [1,2,3,5]
```
> 5 is after 3, 5 is inserted after 3.

2023-07-08 10:10 UTC, levirs565 commented
@aarthificial Are you accept the tweening algorithm? If not, please give me Suggestion about tweening algoritm

2023-07-10 18:49 UTC, Firnael commented
Hi @levirs565 , with this final part merged, will LaTex tweening be finally possible ?
Thank you for your work here.

2023-07-13 03:12 UTC, hhenrichsen commented on packages/2d/src/utils/diff.ts
> +    let currentArray = map.get(current.id);
nit: I don't know if this is any better, but this is one line shorter and preserves immutability:
```tsx
const currentArray = map.get(current.id) ?? [];
if (!map.has(current.id)) {
    map.set(current.id, currentArray);
}
```

2023-07-13 03:12 UTC, hhenrichsen commented on packages/2d/src/components/SVG.ts
> +      )!;
Generally, I dislike the `!` operator to unnull something, especially because you effectively check for nulls on the next line anyways.

2023-07-16 07:44 UTC, levirs565 commented
> Hi @levirs565 , with this final part merged, will LaTex tweening be finally possible ? Thank you for your work here.

Yes, Latex tweening will be possible. How we insert new node when Tweening SVG is not affecting Latex tweening. Insertion order when tweening Latex is not important.

2023-07-16 10:34 UTC, levirs565 commented
In my opinion, this pull request are ready

2023-07-22 06:16 UTC, ksassnowski requested changes
When trying to tween between SVGs that use `stroke-linecap="round"` and/or `stroke-linejoin="round"`, the line cap and line join get discarded during the tween, then suddenly get reapplied after the tween has finished.

Code to reproduce 

```ts
import {makeScene2D} from '@motion-canvas/2d';
import {createRef} from '@motion-canvas/core';
import {SVG} from '@motion-canvas/2d/lib/components/SVG';

const icon1 = `
<svg width="128" height="128" fill="none" viewBox="0 0 24 24">
  <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="1.5" d="M16.75 17.25H17.25C18.3546 17.25 19.25 16.3546 19.25 15.25V6.75C19.25 5.64543 18.3546 4.75 17.25 4.75H6.75C5.64543 4.75 4.75 5.64543 4.75 6.75V15.25C4.75 16.3546 5.64543 17.25 6.75 17.25H7.25"></path>
  <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="1.5" d="M12 15.75L9 19.25H15L12 15.75Z"></path>
</svg>
`;

const icon2 = `
<svg width="128" height="128" fill="none" viewBox="0 0 24 24">
  <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="1.5" d="M4.75 8.75C4.75 7.64543 5.64543 6.75 6.75 6.75H15.25C16.3546 6.75 17.25 7.64543 17.25 8.75V15.25C17.25 16.3546 16.3546 17.25 15.25 17.25H6.75C5.64543 17.25 4.75 16.3546 4.75 15.25V8.75Z"></path>
  <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="1.5" d="M17.75 10.75H18C18.6904 10.75 19.25 11.3096 19.25 12V12C19.25 12.6904 18.6904 13.25 18 13.25H17.75"></path>
</svg>
`;

export default makeScene2D(function* (view) {
  const svg = createRef<SVG>();

  view.add(<SVG ref={svg} svg={icon1} stroke={'white'} />);

  yield* svg().svg(icon2, 1);
});
```

https://github.com/motion-canvas/motion-canvas/assets/5139098/07d10e9b-3f8a-4d5e-8cf3-610d02f615eb


I'm not sure if this is something we can realistically fix, though.

2023-07-22 06:16 UTC, ksassnowski commented on packages/2d/src/components/SVG.ts
> +import {SignalValue, SimpleSignal} from '@motion-canvas/core/lib/signals';
An export for this component should also be added to `packages/2d/src/components/index.ts`

2023-07-22 06:16 UTC, ksassnowski commented on packages/2d/src/components/SVG.ts
> +  protected *generateTransformator(
`Transformator` -> `Transformer`. There are a few other occurrences like this in the PR.

2023-07-22 06:16 UTC, ksassnowski commented on packages/2d/src/components/SVG.ts
> +    const newValue = typeof value === 'string' ? value : value();
Should use
```ts
import { isReactive } from '@motion-canvas/core';

const newValue = isReactive(value) ? value() : value;
```

2023-07-22 06:30 UTC, ksassnowski commented
I also think that the `SVG` component should use the node's `size` signal (if provided) to set the `width` and `height` of the actual SVG DOM node. From what I can tell, you have to explicitly change the `width` and `height` attributes of the actual SVG string if you want to make it smaller or larger at the moment.

2023-07-23 11:03 UTC, levirs565 commented on packages/2d/src/components/SVG.ts
> +  private static getElementStyle(
SVG has `opacity` attribute. This property must converted to MotionCanvas `opacity` property instead of `stroke-opacity`.

2023-07-23 11:37 UTC, levirs565 commented on packages/2d/src/components/SVG.ts
> +  private static getElementStyle(
I cannot find MotionCanvas property that is simmiliar to SVG `stroke-opacity` property.

2023-07-23 11:53 UTC, levirs565 commented
> 



> When trying to tween between SVGs that use `stroke-linecap="round"` and/or `stroke-linejoin="round"`, the line cap and line join get discarded during the tween, then suddenly get reapplied after the tween has finished.
> 
> Code to reproduce
> 
> ```ts
> import {makeScene2D} from '@motion-canvas/2d';
> import {createRef} from '@motion-canvas/core';
> import {SVG} from '@motion-canvas/2d/lib/components/SVG';
> 
> const icon1 = `
> <svg width="128" height="128" fill="none" viewBox="0 0 24 24">
>   <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="1.5" d="M16.75 17.25H17.25C18.3546 17.25 19.25 16.3546 19.25 15.25V6.75C19.25 5.64543 18.3546 4.75 17.25 4.75H6.75C5.64543 4.75 4.75 5.64543 4.75 6.75V15.25C4.75 16.3546 5.64543 17.25 6.75 17.25H7.25"></path>
>   <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="1.5" d="M12 15.75L9 19.25H15L12 15.75Z"></path>
> </svg>
> `;
> 
> const icon2 = `
> <svg width="128" height="128" fill="none" viewBox="0 0 24 24">
>   <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="1.5" d="M4.75 8.75C4.75 7.64543 5.64543 6.75 6.75 6.75H15.25C16.3546 6.75 17.25 7.64543 17.25 8.75V15.25C17.25 16.3546 16.3546 17.25 15.25 17.25H6.75C5.64543 17.25 4.75 16.3546 4.75 15.25V8.75Z"></path>
>   <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="1.5" d="M17.75 10.75H18C18.6904 10.75 19.25 11.3096 19.25 12V12C19.25 12.6904 18.6904 13.25 18 13.25H17.75"></path>
> </svg>
> `;
> 
> export default makeScene2D(function* (view) {
>   const svg = createRef<SVG>();
> 
>   view.add(<SVG ref={svg} svg={icon1} stroke={'white'} />);
> 
>   yield* svg().svg(icon2, 1);
> });
> ```
> 
>  svgtween.mp4 
> I'm not sure if this is something we can realistically fix, though.

The problem is not from SVG component but from Path component. To fix this issue you must make Path interpolation precision higher (lower number). By default path component interpolation precision is 5. When we set this to 1, this issue will fixed.

Currently, to change the precision we must edit [`createCurveProfileLerp.ts`](https://github.com/motion-canvas/motion-canvas/blob/main/packages/2d/src/curves/createCurveProfileLerp.ts) file. Below are place of the precision:

```ts
export function createCurveProfileLerp(a: CurveProfile, b: CurveProfile) {
  const interpolations = getInterpolationPolygon(a, b, 5, 4);
  // more
}
```

The precision is 5. Maybe, we must allow user to change the interpolation precision.

2023-07-23 14:34 UTC, levirs565 commented
> I also think that the `SVG` component should use the node's `size` signal (if provided) to set the `width` and `height` of the actual SVG DOM node. From what I can tell, you have to explicitly change the `width` and `height` attributes of the actual SVG string if you want to make it smaller or larger at the moment.

Current available way to change width or height we can change SVG wrapper scale.

```ts
svg().wrapper.scale([2, 1]);
````

2023-07-24 03:58 UTC, levirs565 commented
> I also think that the `SVG` component should use the node's `size` signal (if provided) to set the `width` and `height` of the actual SVG DOM node. From what I can tell, you have to explicitly change the `width` and `height` attributes of the actual SVG string if you want to make it smaller or larger at the moment.

Now, we can change SVG size with `width` or `height` property. When only `width` or only `height` property are specified, unspecified property will follow specified property and SVG document actual aspect ratio.

2023-08-15 14:59 UTC, levirs565 commented
Is there anything that needs to be fixed in this PR?

2023-08-22 03:15 UTC, aarthificial requested changes
Apologies for the delay.
I left some comments, mostly about the documentation.
I'd genuinely recommend using some free grammar checker because there's a lot of mistakes that could be easily picked up by such software.

There are also some problems with the implementation:
- tweening between two `polygon`s doesn't seem to work.
- percentage size is not supported (`width={'50%'}`, etc).

But I think we can fix them in future PRs to get this one done.

2023-08-22 03:15 UTC, aarthificial commented on packages/2d/src/components/SVG.ts
> +  ): Generator<ThreadGenerator> {
```suggestion
   * Create a tweening list to tween between two SVG nodes.
   * @param from - The initial node,
   * @param to - The final node.
   * @param duration - The duration of the tween.
   * @param timing - The timing function.
   */
  protected *generateTransformer(
    from: Node,
    to: Node,
    duration : number,
    timing: TimingFunction,
  ): Generator<ThreadGenerator> {
```

2023-08-22 03:15 UTC, aarthificial commented on packages/2d/src/components/SVG.ts
> +   * @returns
```suggestion
   * Get the current `SVGDocument`.
```

2023-08-22 03:15 UTC, aarthificial commented on packages/2d/src/components/SVG.ts
> +   * Get current document nodes
```suggestion
   * Get current document nodes.
```

2023-08-22 03:15 UTC, aarthificial commented on packages/2d/src/components/SVG.ts
> +   * @returns Converted Shape properties
```suggestion
   * Convert SVG colors in Shape properties to Motion Canvas colors.
   * @param param - Shape properties.
   * @returns Converted Shape properties.
```

2023-08-22 03:15 UTC, aarthificial commented on packages/2d/src/components/SVG.ts
> +
```suggestion
  /**
   * Parse an SVG string as `SVGDocumentData`.
   * @param svg - And SVG string to be parsed.
   * @returns `SVGDocumentData` that can be used to build SVGDocument.
   */
```

2023-08-22 03:15 UTC, aarthificial commented on packages/2d/src/components/SVG.ts
> +   */
```suggestion
  /**
   * Convert the SVG element's style to a Motion Canvas Shape properties.
   * @param element - An SVG element whose style should be converted.
   * @param inheritedStyle - The parent style that should be inherited.
   */
```

2023-08-22 07:54 UTC, levirs565 commented
> tweening between two polygons doesn't seem to work.

In order to support this feature, the `Line` component must support `points` tweening. This must implemented in other PR.

> percentage size is not supported

When we can get calculated size, we can support percentage size. This can implemented in other PR. Latex tweening does not need this feature.

2023-08-22 18:34 UTC, aarthificial commented
> In order to support this feature, the Line component must support points tweening. This must implemented in other PR.

Yes, but `Line` already has limited support for tweening (when arrays have the same size, for example), but the `points` property is not accounted for by the `generateTransformer()` method so even that doesn't work.

> When we can get calculated size, we can support percentage size.

We'll never be able to get "calculated size" because the point of the `desiredSize` function is to provide the basis for layout calculations. If you try to get the calculated size at that point you'll create a circular dependency which I'm sure you've noticed already. Classes like `Img` and `Video` are good examples of using `ratio` to support percentage sizes.

2023-08-22 18:34 UTC, aarthificial approved these changes

2023-08-22 18:35 UTC, merged

2023-08-22 18:35 UTC, aarthificial commented
Anyway, thanks for the PR!