Fix OUTPUT DIRECTORY button on WSL
motion-canvas/motion-canvas pull request #787
Opened 2023-08-02 07:19 UTC by SleeklyCoding

This is a PR regarding the OUTPUT DIRECTORY button located in the player's video settings.

When we run `npm` on WSL (Windows Subsystem for Linux) then Motion Canvas tries to execute:
`xdg-open <absolute-path-to-output-dir>`

In the case of WSL it won't work, so we can do something like this:
`bash -c cd <absolute-path-to-output-dir> && explorer.exe .`

2023-08-22 01:15 UTC, aarthificial requested changes
Since the `explorer` variable no longer makes sense with WSL, I recommend we rewrite this method a bit to avoid this confusing `explorer === 'bash'` check at the end:
```ts
export function openInExplorer(file: string) {
  let command: string | null = null;
  let args = [file];
  const os = platform();

  switch (os) {
    case 'win32':
      command = 'explorer';
      break;
    case 'linux':
      if (isRunningOnWSL()) {
        command = 'bash';
        args = ['-c', `cd ${file} && explorer.exe .`];
      } else {
        command = 'xdg-open';
      }
      break;
    case 'darwin':
      command = 'open';
      break;
  }

  if (command) {
    spawn(command, args, {detached: true}).unref();
  } else {
    console.warn(`Unsupported OS: ${os}`);
  }
}
```

2023-08-27 11:52 UTC, SleeklyCoding commented on packages/vite-plugin/src/openInExplorer.ts
> +  }
Moved to packages/vite-plugin/src/main.ts

2023-08-27 11:54 UTC, SleeklyCoding commented
I did force-push because I initially forgot to add --fixup flag during committing.

2023-10-04 06:04 UTC, aarthificial approved these changes

2023-10-18 05:58 UTC, merged