docs: improve `Path` documentation
motion-canvas/motion-canvas pull request #838
Opened 2023-11-11 16:42 UTC by squigglesdev

Improved the clarity of the docs for the `Path` component.

2023-11-14 20:49 UTC, aarthificial requested changes

2023-11-14 20:49 UTC, aarthificial commented on packages/docs/docs/components/path.mdx
> +The `Path` allows us to draw and animate SVG paths.
```suggestion
The `Path` node allows us to draw and animate SVG paths.
```

2023-11-14 20:49 UTC, aarthificial commented on packages/docs/docs/components/path.mdx
> +intuitive control of the path, and control each point within Motion Canvas, we reccomend checking out the [`Spline`][spline] component.
```suggestion
`Path` nodes are great for displaying precalculated SVG paths, but the format can be confusing. If you want to have more
intuitive control of the path, and control each point within Motion Canvas, we recommend checking out the [`Spline`][spline] component.
```

2023-11-14 20:49 UTC, aarthificial commented on packages/docs/docs/components/path.mdx
> +We can specify the path to be displayed by setting the data property of the Path component:
```suggestion
We can specify the path to be displayed by setting the `data` property of the `Path` node:
```

2023-11-14 20:49 UTC, aarthificial commented on packages/docs/docs/components/path.mdx
> +    ></Path>,
```suggestion
    />,
```

2023-11-14 20:49 UTC, aarthificial commented on packages/docs/docs/components/path.mdx
> +a `getPointAtPercentage` method that can be used to animate an object along it.
I'd change this to something like:
```suggestion
Like all nodes extending the [`Curve`][curve] class, the `Path` node has
a `getPointAtPercentage` method that can be used to animate an object along it:
```

2023-11-17 15:22 UTC, squigglesdev commented
I've added your suggestions, and actually remembered to run prettier this time 😅

2023-11-22 07:51 UTC, aarthificial requested changes

2023-11-22 07:51 UTC, aarthificial commented on packages/docs/docs/components/path.mdx
> +  );
This codeblock contains invalid TS code which is why the verification is not passing.
You're missing the closing brackets:
```suggestion
  );
});
```

2023-11-22 07:51 UTC, aarthificial commented on packages/docs/docs/components/path.mdx
> +Like all nodes extending the [`Curve`][curve] class, the `Path` node has a
``[`Curve`][curve]`` is a [reference-style link](https://www.markdownguide.org/basic-syntax/#reference-style-links), it assumes that the actual link to `curve` is defined somewhere at the bottom of the file:
```md
[curve]: /api/2d/components/Curve
```

2024-05-16 06:35 UTC, aarthificial approved these changes

2024-05-16 07:50 UTC, merged

2024-05-16 09:57 UTC, squigglesdev commented
Whoops kinda forgot about this, thanks for finishing it off for me 😅

2024-05-16 10:01 UTC, aarthificial commented
@squigglesdev No worries!